name = "Trashcans Skyblock Pack"
author = "Trashcan_420"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1dec7cb029900a3fc96b602179e494adae8ca94b1349c1f104e40ce1c61f983"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
