name = "Trashcans Skyblock Pack"
author = "Trashcan_420"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5109c77ab5150057978dbcc7452127e85e210fc68901535d9be3466eab6296ec"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
